apiVersion: v1
kind: Service

metadata:
  name: devops-k8s-app
  namespace: devops-demo

spec:
  selector:
    app: devops-k8s-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: ClusterIP